### ISSUE TITLE
还是需要科学上网

### ISSUE THREAD

**Issue by JIM4ME** [ZuodaoTech/everyone-can-use-english#1023]
这个能在下个版本解决吗？目前有替代方式吗？

**Comment by an-lee** [comment]
解决不了。

**Comment by sniperboy0829** [comment]
@JIM4ME 有兴趣可以尝试下iOS App [独白-人人都是多语者](https://apps.apple.com/app/id6648770338)，无需科学上网，用同样的理念开发而来，手机使用更方便。https://apps.apple.com/app/id6648770338
