### ISSUE TITLE
更新 1000-hours/sounds-of-american-english 外链文件

### ISSUE THREAD

**Issue by bluechallenge** [ZuodaoTech/everyone-can-use-english#1025]
笑来老师、导演好，因为不确定能否直接通过PR来更新外链文件（内容），请允许我借 issue 来跟进两个外链文件的小问题，如果不合适就麻烦帮忙挪到讨论区去，感谢 :-)

### 8.2-cepd-phonetics-and-sound.md

1. 更新：camsd --> camkd

> camsd：用浏览器打开 CEPD 真人示范录音（英式发音）在线网址

2. **_CEPD-phonetic-transcription.alfredworkflow_** 文件更新如下：

a) 删除camsd 和 camkd 对应Python脚本里 `import vlc`

> 会提示 “import vlc” 找到不到模块，删掉就可以顺利打开发音网页，不确定是不是因为我电脑（macOS Ventura 13.6.9, Python 3.9.6）版本比较老。

b) workflow 启动关键字（除了 ipa）对应的 Title 都一样，需根据具体功能相应更新。

### 8.4-daily-speech-exercises.md

**_8.4-daily-speech-exercises.zip_** 文件更新如下：

1. 删除冗余参数

`%pip install  openai --upgrade openai --> %pip install --upgrade openai`

3. 更新 'ending_file' 参数路径：_ending_file="ending.mp3"_ --> ending_file="**resources/ending.mp3**"

```
for p in ["alloy", "nova"]:
    audio_filename = get_openai_tts_audio(rspd, file_name=f'{audio_filename_prefix}-{p}.mp3', performer=p, silence_duration=1500, with_ending=True, ending_file="ending.mp3")
```

4. 更新 'Artwork.png'：'_Artwork.png_' --> '**resources/Artwork.png**'

`add_metadata(whole_audio_filename, 'Artwork.png', 'tts', 'Daily Speech Training - Conversations', 'SPEECH')`

5. 为了方便配置OpenAI API 相关信息且兼顾安全性，在当前 **_.ipynb_** 文件同级目录下，创建 .env 文件，由读者自行配置 `OPENAI_API_KEY` 和 `OPENAI_BASE_URL`.
6. desing --> design

> _You'll desing two conversations or debates_

7. 取消注释生成对话的 user_prompt
```
user_prompt = """
on homosexuality, Although we don't oppose homosexuality, we do have another concern—what if our child isn't naturally homosexual but is somehow influenced to become one? How should we view this situation, and how can we prevent it from happening?
"""
```

8. 清除所有单元格的输出

附上更新后的 _8.4-daily-speech-exercises.md_ 文件：[8.4-daily-speech-exercises_updated_0830.zip](https://github.com/user-attachments/files/16811340/8.4-daily-speech-exercises_updated_0830.zip)

**Comment by xiaolai** [comment]
我找时间看看直接改一下算了。

**Comment by xiaolai** [comment]
@bluechallenge Done!
