### ISSUE TITLE
软件设置中没有词典设置选项

### ISSUE THREAD

**Issue by pluoluo** [ZuodaoTech/everyone-can-use-english#1049]
帮助文档中，软件设置里是有词典设置的，但在APP中没有词典设置选项，所以不能选择词典。
我的APP版本是windows的0.4.1

**Comment by an-lee** [comment]
下个版本就有了，还没发布。这两天就会发布。
文档先更新了。

**Comment by an-lee** [comment]
v0.5.0 版本已经发布，支持了词典。

**Comment by pluoluo** [comment]
已更新，感谢！
