### ISSUE TITLE
本地词典中的声音播放，引起windows找到不应用提示

### ISSUE THREAD

**Issue by pluoluo** [ZuodaoTech/everyone-can-use-english#1059]
点击本地词典中的任意声音播放按钮，都会弹出这个提示，而且是每次点击都会弹出。
声音能正常播放。
在线词典没有这个问题
![image](https://github.com/user-attachments/assets/2ebb310f-073e-41dd-98c2-c5984e88b6da)

**Comment by an-lee** [comment]
v0.5.1 中已经修复。
