### ISSUE TITLE
v0.5.0重新打开软件，http代理会失效

### ISSUE THREAD

**Issue by rodingbaba** [ZuodaoTech/everyone-can-use-english#1064]
版本 v0.5.0
描述：软件配置了http代理，关闭软件后，重新打开软件，http代理处获取到的ip为国内的ip（如图一），代理没有生效，点击按钮关闭代理设置，再打开，刷新后才能获取到美国的代理ip（如图二）

图一：
![20240912161925-sz](https://github.com/user-attachments/assets/bb0acb8f-d3f6-4bd0-af35-9756474d8aab)

图二：

![20240912162013-us](https://github.com/user-attachments/assets/693a0a53-41e3-49b4-a57f-7c8f65c4314a)

**Comment by rodingbaba** [comment]
v0.5.2版本问题依然存在，重新打开软件，还是不会默认使用代理，需要手工开关代理设置才会生效。

**Comment by an-lee** [comment]
Fixed in https://github.com/ZuodaoTech/everyone-can-use-english/commit/9e974e977eccd33c01907ad557c5d4fb14f6132b
