### ISSUE TITLE
排版需要优化

### ISSUE THREAD

**Issue by JIM4ME** [ZuodaoTech/everyone-can-use-english#1080]
出现了一个单词被拆成两行，之前的版本好像没有出现这种排版错误

<img width="793" alt="截屏2024-09-11 20 53 25" src="https://github.com/user-attachments/assets/1d892b8c-77c3-49f3-8388-823e4b7f19d9">

**Comment by an-lee** [comment]
什么版本？v0.5.0 之后的版本应该修复了。
