### ISSUE TITLE
0.5.2 在使用代理github登录，打开网页并输入验证码，会跳enjoy会卡死在主页面

### ISSUE THREAD

**Issue by seejv** [ZuodaoTech/everyone-can-use-english#1093]
1、设置代理（香港、美国、日本）
2、使用 github 进行登录(跳转到浏览器打开）
3、输入 github 验证码 (不用输入，等一会 enjoy 自己就白屏了）
4、enjoy 一片空白
5、等待 30S 依旧空白
6、关闭，重启
7、重新回到登录界面

![image](https://github.com/user-attachments/assets/e07e4039-1701-4775-8685-d292f710a502)
![image](https://github.com/user-attachments/assets/6a30e355-2870-4051-9157-0e1f081c84d3)

**Comment by an-lee** [comment]
确实是有 bug，现在修好了，你再试试？

**Comment by an-lee** [comment]
> > 确实是有 bug，现在修好了，你再试试？
> 
> 我只能等新版本发布再用了，源码没有编译步骤。

是服务器的 bug，现在已经可以正常用了。
