### ISSUE TITLE
改变whisper模型，检查无法通过

### ISSUE THREAD

**Issue by gosber** [ZuodaoTech/everyone-can-use-english#1094]
无论下载多少次模型，下载完只要是切换模型，就会转圈：Checking whisper status
切回tiny也是报错：• Whisper is not working

另外whisper.cpp太慢了，建议macOS上(m芯片上）默认可以指定使用mlx_whisper.

OS: macOS 15.0 (24A335)
Mem: M1 Max 64GB

**Comment by an-lee** [comment]
用新版 v0.6.0 再试试看。
