### ISSUE TITLE
TTS生成音频不成功，钱却扣了两次

### ISSUE THREAD

**Issue by zzern** [ZuodaoTech/everyone-can-use-english#1096]
在将短文使用TTS服务时，一直在生成（转圈圈图标），最后没有音频出现

**Comment by an-lee** [comment]
应该是有报错吧？

**Comment by an-lee** [comment]
你帐号 ID 多少？我查一下看，如果多扣了费，给你补回来。

**Comment by zzern** [comment]
24019411    不知道是不是网络问题？还是余额不够？生成之前是有余额的，生成完成之后音频没有出现而且余额也变负了。

**Comment by an-lee** [comment]
你输入的文本是不是比较长？

**Comment by zzern** [comment]
稍微长了一些，不过也没提示过长什么的，如果是过长，是不是需要在调用tts服务前去检查一下文本长度，长度符合才去调用tts？而不是直接丢给tts去生成

**Comment by an-lee** [comment]
> 稍微长了一些，不过也没提示过长什么的，如果是过长，是不是需要在调用tts服务前去检查一下文本长度，长度符合才去调用tts？而不是直接丢给tts去生成

研究了一下，这个问题应该是这样。现在服务器是挂在 cloudflare 后面，但是 cloudflare 的响应时间只有 100 秒，如果 openai 的 tts 响应时间超过 100 秒，cloudflare 这边先给客户端报超时了，但是 openai 那边会正常完成扣费，只是没有返回到客户端这边。

我研究下怎么解决。建议长文本的可以先用 azure 的 tts，这个是用 websocket 连接，不会有这个问题。

**Comment by an-lee** [comment]
后台查了你用的是 openai tts。
给你返了 0.1 美金。
这个问题我再修复一下。

**Comment by an-lee** [comment]
> 研究了一下，这个问题应该是这样。现在服务器是挂在 cloudflare 后面，但是 cloudflare 的响应时间只有 100 秒，如果 openai 的 tts 响应时间超过 100 秒，cloudflare 这边先给客户端报超时了，但是 openai 那边会正常完成扣费，只是没有返回到客户端这边。

这个问题已经解决，在 cloudflare 超时 100 秒之前，客户端会收到超时并提示重试，服务端完成请求之后会将结果缓存，客户端重新请求会得到结果，不会重复请求和扣费。
