### ISSUE TITLE
默认AI引擎能否自定义？

### ISSUE THREAD

**Issue by lx277856602** [ZuodaoTech/everyone-can-use-english#1100]
目前的默认AI引擎支持Openai与Enjoyai两种类型，能否开放权限，支持更多AI引擎呢？比如说ollama等

**Comment by supermayx** [comment]
只要支持openai api格式的ai服务都可以用，市面上有很多，你可以查询一下，比如deepseek

**Comment by lx277856602** [comment]
> 只要支持openai api格式的ai服务都可以用，市面上有很多，你可以查询一下，比如deepseek

感谢！

**Comment by rodingbaba** [comment]
大家有什么推荐的AI引擎吗，价格便宜的
