### ISSUE TITLE
刚完成新的版本更新又出现了无法连接网络的错误的提示

### ISSUE THREAD

**Issue by thinkbankcoin** [ZuodaoTech/everyone-can-use-english#1146]
看一下我的截图，打开梯子和关闭梯子都不行
<img width="578" alt="截屏2024-10-22 21 56 17" src="https://github.com/user-attachments/assets/f7476bfa-16f9-4553-9ab8-854a0233c373">

**Comment by an-lee** [comment]
Proxy Settings 设置不对吧，这地址咋来的？一般是 http://localhost:xxxx

**Comment by thinkbankcoin** [comment]
这个Proxy是这样的
tg://socks?server=127.0.0.1&port=1080&user=&pass=
这个地址是我看完FAQ之后，然后更改了API，Proxy是原来就有的，没有的更改过。
在FAQ里没有提示更改Proxy,也没有提示Proxy具体的地址。
这个Proxy的具体地址是要找VPN的供应商提供吗？

**Comment by thinkbankcoin** [comment]
我问了VPN商家，他说他们不用代理。我把代理设置关闭了，就成功登录了。
但我还是有疑问，就是只要我每次更新Enjoy后，都会出现网络错误。然后一直以为是代理设置有问题。但只要过两天，把代理设置关闭后，恢复原来的设置就可以成功登录。我不知道这是为什么？
![Uploading 截屏2024-10-25 02.53.04.png…]()
