### ISSUE TITLE
OpenAI 提供的 api key 无法使用

### ISSUE THREAD

**Issue by mysteryven** [ZuodaoTech/everyone-can-use-english#1147]
我在设置里面添加了 OpenAI 提供的 api key，但是新建 AI assistant 的时候，无法正常运行，提示：

![CleanShot 2024-10-23 at 08 28 55@2x](https://github.com/user-attachments/assets/f39a6b7a-ceae-411a-817f-7dd3ec2514d3)

我尝试了 project key 和 api key 都不行，权限也都给了。充值后，使用 enjoy 提供的模型可以。

**Comment by an-lee** [comment]
说明你的 key 就是不能用啊……或者不支持 gpt-4o 这个模型。
OpenAI 的 key 需要绑卡才能用的，参考 OpenAI 的官方文档吧。
