### ISSUE TITLE
Mac M1 Pro 0.6.1音频转文本崩溃 必现

### ISSUE THREAD

**Issue by freeyob** [ZuodaoTech/everyone-can-use-english#1178]
如下图，用本地下载好的引擎ggml-large-v3.bin语音转文本崩溃，之前好好的。

<img width="1001" alt="Screenshot 2024-11-13 at 2 36 00 PM" src="https://github.com/user-attachments/assets/31c53a51-238e-4072-9fd0-72416e4637cf">

**Comment by freeyob** [comment]
回退到0.5.2恢复了正常

**Comment by an-lee** [comment]
是选择了 large-v3 还是 large-v3-turbo ？

**Comment by an-lee** [comment]
> large-v3-turbo

0.6 版的 whisper 引擎改了，查了一下，确实是不支持 large 模型，先改用小一点的模型吧。
下个版本会再优化一下

**Comment by freeyob** [comment]
https://github.com/ZuodaoTech/everyone-can-use-english/releases/tag/v0.7.0 新版本增加了选择，解决了问题。
