### ISSUE TITLE
v0.6.1语音转文本错误

### ISSUE THREAD

**Issue by crazy-airhead** [ZuodaoTech/everyone-can-use-english#1183]
版本v0.6.1
系统 mac m1 v15.1
导入语音正常，点击语音开始转义成文本的时候报错，使用的是本地的tiny.en模型，旧版本是0.5.2正常。
<img width="602" alt="image" src="https://github.com/user-attachments/assets/3663de83-79ee-459e-afef-7bc92ed388c7">

**Comment by an-lee** [comment]
每一条音频都这样报错吗？

**Comment by crazy-airhead** [comment]
是的

**Comment by an-lee** [comment]
用 Azure AI 呢？会报一样的错误吗？

**Comment by crazy-airhead** [comment]
不会

**Comment by crazy-airhead** [comment]
0.7.0版本可以了
