### ISSUE TITLE
无法收到邮箱验证码，登陆不进去了

### ISSUE THREAD

**Issue by SkyPan19** [ZuodaoTech/everyone-can-use-english#1187]
几天没用这个app，今天点进去，提示要”重新登录“，可是我重新登入的时候，输入之前绑定的QQ邮箱后，收不到验证码了，无法重新登陆。
![Uploading 屏幕截图 2024-11-18 140218.png…]()

**Comment by an-lee** [comment]
我看邮件发送系统是正常的，你检查一下你邮箱的垃圾箱、设置之类的？重试一下看看？

**Comment by SkyPan19** [comment]
> 我看邮件发送系统是正常的，你检查一下你邮箱的垃圾箱、设置之类的？重试一下看看？
已解决，谢谢！
