### ISSUE TITLE
安装异常，无法启动

### ISSUE THREAD

**Issue by bc1qZ** [ZuodaoTech/everyone-can-use-english#1192]
下载完以后安装时出现图片中这个样子。
![1732072152950](https://github.com/user-attachments/assets/b4b91767-25dd-4641-873d-c0a720cb556a)

这种图片加载完以后应该是安装完成了，但是无法启动。点了APP没有反应

我尝试把所有旧版本相关的文件都删除，可还是这样。

**Comment by bc1qZ** [comment]
我是Window系统

**Comment by an-lee** [comment]
试试这样，先把旧版本删除，重启电脑，然后再安装一次看看

**Comment by bc1qZ** [comment]
> 试试这样，先把旧版本删除，重启电脑，然后再安装一次看看

我尝试了但是安装时候还是一样

**Comment by bc1qZ** [comment]
> 试试这样，先把旧版本删除，重启电脑，然后再安装一次看看

![1732241223890](https://github.com/user-attachments/assets/6d4e2055-c5f5-4d82-9239-3ee1f5ff5bf0)
meic
每次启动的时候会跳出这个，我把安全防护关了以后可以启动了。
这个应该怎么处理啊

**Comment by bc1qZ** [comment]
![1732241466314](https://github.com/user-attachments/assets/3951d59d-d69e-47f3-975b-cc6e6ede0558)
只要开启防护启动，就会有这个报错

**Comment by bc1qZ** [comment]
我已经更改访问权限可以正常启动了。但是每次有新版本都需要额外添加，除非把这个受控访问权限给关掉。

**Comment by an-lee** [comment]
> 我已经更改访问权限可以正常启动了。但是每次有新版本都需要额外添加，除非把这个受控访问权限给关掉。

因为 Enjoy 软件没有向微软认证签名，所以有安全提示是正常的，安装的时候选择信任就可以了。
