### ISSUE TITLE
启动时提示 ENOENT: no such file or directory

### ISSUE THREAD

**Issue by flynncao** [ZuodaoTech/everyone-can-use-english#1206]
版本：0.7.3（latest）
系统：Windows 10 22H2

![image](https://github.com/user-attachments/assets/3866271e-d391-499d-976e-40a155e943d5)
 
启动的时候碰到的，昨天还使用正常的。不记得修改过任何设置，仅正常shadowing。

点击这个reset all 后依然会回到这个界面。

---

我去检查了了这个目录下的`enjoy_database.sqlite`文件是存在的。

**Comment by an-lee** [comment]
是不是因为 `backup` 这个文件夹没了？

**Comment by flynncao** [comment]
> 是不是因为 `backup` 这个文件夹没了？

有的，里面文件都还在

![image](https://github.com/user-attachments/assets/3f8bc89e-7752-4943-a6fd-730c3568f900)

**Comment by an-lee** [comment]
发布了 `v0.7.4`，简单处理了一下，你更新试试看。

**Comment by flynncao** [comment]
> 发布了 `v0.7.4`，简单处理了一下，你更新试试看。

排查了下原因，是因为Windows Security（Defender）引起的，但我不知道怎么触发的，解禁这个就修复了。

![image](https://github.com/user-attachments/assets/34877339-e008-4974-9923-5a1f4e714da1)

总之感谢！
