### ISSUE TITLE
跟读句子时，按下空格不一定会播放当前句子。

### ISSUE THREAD

**Issue by mysteryven** [ZuodaoTech/everyone-can-use-english#1209]
1. 在影子跟读模式，选中一个句子，播放。
2. 等待播放完毕，按下空格让其继续播放
3. 重复 Step 2。
4. 期望时一直播放这一个句子。实际表现是重复多次后会跳到下一个句子。

此问题从 V6 版本就有了。

**Comment by mysteryven** [comment]
不是每次按空格都必现。我往往有大致这个操作流程：

我用鼠标点击了第一个句子，然后按空格播放，播放了很多遍；

我准备学习第二个句子，鼠标点击第二个句子，按空格开始播放，因为我要背很多遍，所以会在播放完了之后，重复很多次空格。此时基本按几次空格就会出现**一次问题**，这个时候我显示的点击一下我背诵的语句，再重复几次空格，它又会出现一下。之后在第三个句子、第四个句子也会出现。

所以我只能每次播放时，要进行操作：先点击一下这个句子，再按空格。这样能保证每次都不会。

**Comment by an-lee** [comment]
好的，我试着重现一下。

**Comment by freeyob** [comment]
我也出现了，mac，经常出现。
