### ISSUE TITLE
一个存在有点久的音频播放问题

### ISSUE THREAD

**Issue by JIM4ME** [ZuodaoTech/everyone-can-use-english#531]
测试过的设备：
1. win 10（保持更新） 8th i5 8g 
2. macbookair m2 8+256

测试enjoy版本：
含目前为 V 0.2.3 在内的数个版本

1个月前一直用第一台设备进行学习。在进行单句循环训练时，有大概会出现音频播放故障，具体现象是：

> 1. 播放一遍之后，无法马上播放下一遍，需要缓冲一定时间，缓冲时间不定
> 2. 并不是每条音频都会出现这种故障现象

以为是设备性能问题，故购买了设备二。测试了近期的两个版本依然有这种故障。

**Comment by an-lee** [comment]
单句循环的时候，每次播放结束是会有一个短暂的停顿，这是故意设置的，并不是故障。

**Comment by JIM4ME** [comment]
> 单句循环的时候，每次播放结束是会有一个短暂的停顿，这是故意设置的，并不是故障。

应该不是。因为同一句话，它的在单句循环时有时候会出现，有时候不会，呈不规律状。

**Comment by JIM4ME** [comment]
https://github.com/xiaolai/everyone-can-use-english/assets/56964139/dc862a2a-5880-4a19-ae3c-09a22b92d42e

**Comment by an-lee** [comment]
看起来应该是有 bug，我查一下。

**Comment by JIM4ME** [comment]
> 看起来应该是有 bug，我查一下。

好的，这个应该是从第一个版本就出现过。当时以为是我自己的电脑性能问题就没太注意

**Comment by JIM4ME** [comment]
v0.2.5 版本依然会

**Comment by JIM4ME** [comment]
v0.2.10 版本依然会

**Comment by JIM4ME** [comment]
v0.3.3 版本依然会

**Comment by an-lee** [comment]
v0.4.0 之后的版本应该修复了。
