### ISSUE TITLE
如何在console里面获取整篇文章的音标

### ISSUE THREAD

**Issue by yanyinn** [ZuodaoTech/everyone-can-use-english#600]
导演，你好：）。请教一个问题。

![E08F4063-1C07-4580-B468-43BC9F6D604E_1_201_a](https://github.com/xiaolai/everyone-can-use-english/assets/109458303/60b32657-3b50-4db7-9394-faa59edd8efe)

点击上图的copyText按钮后，剪贴板可以得到类似如下文本

But(bˌʌt) each(ˈiːtʃ · əv) of() us(ˌʌs) also(ˈɔːlsoʊ) has(həz) our(ˌaʊɚr) individual(ˌɪndi:vˈɪdʒuːəl) version(vˈɝːʒən) of(ʌv) the(ðə) world(wˈɝːld) the(ðə) quality(kwˈɔli:ti) of(ʌv) which(wˈɪtʃ) depends(di:pˈendz) on(ˌɔn) our(ˌaʊɚr) own(ˈoʊn) personal(pˈɝːsənəl) quality(kwˈɔli:ti)

但我想把内容按照enjoy窗口里面实际显示的那样（如下）用打印机打印出来，方便练习。

<img width="477" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/109458303/6f0f89e7-a1dd-4f91-9d49-aa93ca16f7e4">

transcript之后，文章被分句了，手动整理就更加麻烦。所以我想问下如何通过chrome的console命令获取整篇文章的文本以及修正后的音标，这样我就可以自己写点代码，重新排版了。

**Comment by an-lee** [comment]
这个不太好弄。可能需要专门做一个全文的显示，再加个导出 PDF 的功能。

**Comment by bluechallenge** [comment]
https://tophonetics.com 可以生成整篇文章的音标，也可以更改音标，试试看能满足你的需求不：

<img width="995" alt="toPhonetics" src="https://github.com/xiaolai/everyone-can-use-english/assets/145031804/b4feb722-896b-4005-b130-c0479febe894">

**Comment by yanyinn** [comment]
> https://tophonetics.com 可以生成整篇文章的音标，也可以更改音标，试试看能满足你的需求不：
> 
> <img alt="toPhonetics" width="995" src="https://private-user-images.githubusercontent.com/145031804/329954050-b4feb722-896b-4005-b130-c0479febe894.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTI3MjUsIm5iZiI6MTcxNTU5MjQyNSwicGF0aCI6Ii8xNDUwMzE4MDQvMzI5OTU0MDUwLWI0ZmViNzIyLTg5NmItNDAwNS1iMTMwLWMwNDc5ZmViZTg5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwOTI3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmE4Y2NlMWRmODRjZTg2YWQyZDdmYWI4ZGRkMjRmNzNjMDllYjg4ODI4NTA3YzMwODA3ZjVlMDllZDI1MmFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MVQFS7IA2fsovfQ-pzQJdLJUeZP1Vh0yVORW_5fKYkY">

感觉比openai生成得好，很有帮助，感谢🙏

**Comment by an-lee** [comment]
v0.3.1 版本已经实现。

![14cd508c-2723-49bc-bc40-4f39257647b0](https://github.com/user-attachments/assets/0e67dd03-b767-4c01-a2ce-9006278bb0f7)
