### ISSUE TITLE
错字 - 精彩且"有"准确的修辞

### ISSUE THREAD

**Issue by jemerci** [ZuodaoTech/everyone-can-use-english#709]
精彩且有准确的修辞, 应为 精彩且又准确的修辞.

https://1000h.org/training-tasks/language.html
第一节第 7 段.

**Comment by xiaolai** [comment]
改了。

**Comment by jemerci** [comment]
错字: 不"能"么正式或者速度较快的时候, 
应为: 不"那"么正式或者速度较快的时候

2.2.9. h
https://1000h.org/sounds-of-american-english/2.2.9-h.html
中文第二段第一行

**Comment by jemerci** [comment]
beggar第二个发音, 女士发音egg, 发音错误, 一点便知.(应该是紧随其后的 egg 混淆了)
![image](https://github.com/user-attachments/assets/d6287b34-e6ff-4681-b2d6-bf58ca2958f2)

位置:
# 2.2.4 k/g
## 拼写（Spellings）
### gg
#### beggar 女士发音


# 疑似 bug
另外发现一个不知算不算 bug 的问题, 页面只有是通过浏览器后退按钮, 即从当前页面返回到上一个页面时, 发音全部不可用.
