### ISSUE TITLE
Retranscribe not work

### ISSUE THREAD

**Issue by heyanlong** [ZuodaoTech/everyone-can-use-english#724]
I click the transcribe action then show dialog, but it's looking not working

version is v0.2.12

**Comment by an-lee** [comment]
Can you post a screenshot? Did an error pop up?

**Comment by heyanlong** [comment]
<img width="1552" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/3367958/a56b98a5-e3a9-40dc-901f-e1b62e366153">
<img width="1552" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/3367958/65367fb5-2981-4477-b343-67af122cd6e9">
<img width="1228" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/3367958/ab26d794-a340-4b34-8dcb-22234afafe07">

**Comment by an-lee** [comment]
Oh, the `transcribe` button in the list has been removed in the latest version (v0.2.13).
