### ISSUE TITLE
感谢作者，请问这个仓库使用什么开源协议？能否添加？

### ISSUE THREAD

**Issue by feitian124** [ZuodaoTech/everyone-can-use-english#731]
在推特上看到无数的推荐后，我终于来这个仓库看了看。
是本好书，也看好 enjoy app。
但是没看到仓库是什么开源协议，能否写明，方便生态建设。

**Comment by lyricat** [comment]
您好，选择了 5e2fdb43b11ed97fb3828183e97ed5cb454f8886
