### ISSUE TITLE
Whisper is not working

### ISSUE THREAD

**Issue by gxhaidao2024** [ZuodaoTech/everyone-can-use-english#738]
**Version**

0.2.13

**Platform**

win32 x64 10.0.22631

**Log**
```
Command failed: "C:\Users\海盗\AppData\Local\Enjoy\app-0.2.13\resources\app.asar.unpacked\.vite\build\lib\whisper\main" --file "C:\Users\海盗\AppData\Local\Enjoy\app-0.2.13\resources\app.asar.unpacked\.vite\build\samples\jfk.wav" --model "D:\文件资料\EnjoyLibrary\whisper\models\ggml-large-v2.bin" --output-json --output-file "D:\文件资料\EnjoyLibrary\cache\jfk"
whisper_init_from_file_with_params_no_state: loading model from 'D:\�ļ�����\EnjoyLibrary\whisper\models\ggml-large-v2.bin'

whisper_init_from_file_with_params_no_state: loading model from 'D:\�ļ�����\EnjoyLibrary\whisper\models\ggml-large-v2.bin'


```

**Comment by an-lee** [comment]
Windows 10 经常有问题，看看能不能升到 windows 11

**Comment by gxhaidao2024** [comment]
我的系统就是WIN11家庭版
。


874237623
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZuodaoTech/everyone-can-use-english"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月30日(星期天) 上午8:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZuodaoTech/everyone-can-use-english] Whisper is not working (Issue #738)





 
Windows 10 经常有问题，看看能不能升到 windows 11
