### ISSUE TITLE
可以建一个社区交流群，方便大家交换意见

### ISSUE THREAD

**Issue by chmod777john** [ZuodaoTech/everyone-can-use-english#745]
非常好的项目。既有技术性，然后场景也相当亲民，star 也已经很多了，应该也有很多人开始用了。可以弄一个社区交流群，方便大家讨论和提出建议。

![image](https://github.com/ZuodaoTech/everyone-can-use-english/assets/146207719/1ce87191-2091-46b0-bdf4-0eee8cb1f979)

**Comment by an-lee** [comment]
我们有社区，分别在 Mixin 和 GitHub。
目前没有在微信建社区的打算。
