### ISSUE TITLE
上传音频文件时提示失败

### ISSUE THREAD

**Issue by WeCanSee** [ZuodaoTech/everyone-can-use-english#755]
有一个MP3文件，大小是84mb，上传时提示上传文件失败，是不是对文件的大小有要求？
<img width="946" alt="image" src="https://github.com/ZuodaoTech/everyone-can-use-english/assets/5372949/f76a34d3-4f39-4d09-b8aa-d149d1382d01">

**Comment by an-lee** [comment]
是的，目前限制不能超过 50M。

**Comment by WeCanSee** [comment]
> 是的，目前限制不能超过 50M。

好的，非常感谢！
