### ISSUE TITLE
请问，音频语音转文字生成的文本，如何可以文本复制？

### ISSUE THREAD

**Issue by WeCanSee** [ZuodaoTech/everyone-can-use-english#763]
我通过语音转文字功能，导入了音频文件生成了文本，但是文本在跟读音频界面-语音文本中，似乎无法进行复制？感谢解答！
<img width="1531" alt="image" src="https://github.com/ZuodaoTech/everyone-can-use-english/assets/5372949/90ba858a-30b4-4312-a32c-5450d78b23b6">

**Comment by tan2meng** [comment]
右侧“跟读框”旁边有对应的复制文本的功能按钮，可以一键复制正在跟读的文本。

**Comment by Zhangjuanlli** [comment]
![image](https://github.com/ZuodaoTech/everyone-can-use-english/assets/68979481/52e7996c-d753-4dc6-b39a-05c108981c3b)
整段语音和文本的下载需要在开始输入时复制下载，形成跟读语音只能复制下载一小段一小段分开复制下载

**Comment by tan2meng** [comment]
> 右侧“跟读框”旁边有对应的复制文本的功能按钮，可以一键复制正在跟读的文本。

如果要复制全文，可以在“语音文本”选项顶部右侧功能按钮选择“修改”复制全文。
<img width="341" alt="捕获" src="https://github.com/ZuodaoTech/everyone-can-use-english/assets/174417618/e68f5d86-43ae-42b4-884c-0c25028ee3c8">

**Comment by jemerci** [comment]
> > 右侧“跟读框”旁边有对应的复制文本的功能按钮，可以一键复制正在跟读的文本。
> 
> 如果要复制全文，可以在“语音文本”选项顶部右侧功能按钮选择“修改”复制全文。 <img alt="捕获" width="341" src="https://private-user-images.githubusercontent.com/174417618/345305307-e68f5d86-43ae-42b4-884c-0c25028ee3c8.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTcyOTEsIm5iZiI6MTcxOTk5Njk5MSwicGF0aCI6Ii8xNzQ0MTc2MTgvMzQ1MzA1MzA3LWU2OGY1ZDg2LTQzYWUtNDJiNC04ODRjLTBjMjUwMjhlZTNjOC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwODU2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjI2MGYwMjE4YTAwZjAyYjU5ZGQyNGZjZmZlNDdkNWI3Yzg2YzA0OGU1MWZiNDlmNDhkODliMDAwMTk2ZjlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8bC-YTuSDn6Ll0AEmQPn7OSccUacLuDgZvySucB9XaI">

好方法.
有点遗憾, 不带音标

**Comment by an-lee** [comment]
v0.3.1 版本已经实现。

![14cd508c-2723-49bc-bc40-4f39257647b0](https://github.com/user-attachments/assets/0e67dd03-b767-4c01-a2ce-9006278bb0f7)
