### ISSUE TITLE
enjoy 音标文字无法同时复制.--2 训练方法_人人都能用英语

### ISSUE THREAD

**Issue by jemerci** [ZuodaoTech/everyone-can-use-english#768]
# 朗读全文功能中, 复制一个音频的文本, 黏贴后音标和原文排版错乱, 无法打印. 

### 黏贴排版结果 1
<img width="301" alt="image" src="https://github.com/ZuodaoTech/everyone-can-use-english/assets/105504077/3db42c95-5057-49b1-b791-04e9a31b4d74">

###  黏贴排版结果 2
<img width="662" alt="复制按钮-单句模式" src="https://github.com/ZuodaoTech/everyone-can-use-english/assets/105504077/8ca5c57d-244e-4394-be2d-e0ddafda8817">

## 文本来源: 复制黏贴操作
<img width="1392" alt="从朗读全文部分复制-黏贴后排版错乱" src="https://github.com/ZuodaoTech/everyone-can-use-english/assets/105504077/b7a60cae-fa24-4b61-a1b6-4cd951ae7fa9">

# 背景:
https://1000h.org/training-tasks/procedures.html页面, 老师说的训练方法无法实现:
在最初尚不熟悉的时候，可以把文本和音标**打印出来**，在纸上用笔做各种标记。

<img width="1020" alt="打印音标-训练方法" src="https://github.com/ZuodaoTech/everyone-can-use-english/assets/105504077/16eea45d-e1d1-4fa8-916b-120ff763a748">

# 入口: 
## ENJOY - 音频 - 跟读音频 - 语音文本 - 字幕右侧下拉菜单 - 朗读全文
<img width="1280" alt="image" src="https://github.com/ZuodaoTech/everyone-can-use-english/assets/105504077/af051d43-3e8e-4241-95a8-12f608344906">

## 全文复制位置:
<img width="1392" alt="复制朗读全文的音标和原文内容" src="https://github.com/ZuodaoTech/everyone-can-use-english/assets/105504077/25f23ab9-c78f-4589-9728-f4bcde882d09">

## 黏贴排版结果, 无法打印以供学习标记使用.

我做了什么:
1. 使用 typora, deepl 对话框, vscode. 黏贴均告失败, 复制出的内容依然不可用
2. 尝试一个句子一个句子的复制, 同样的排版问题
3. 临时解决方案: 使用截长屏功能打印.
4. 试用了GPT, Claude, gemini 以及 bing Chat 进行排版, bing 初级排版效果最好, 但有遗漏. 
Cluaude 综合能力最强, 最终可以输出可用的打印文本.
对原始黏贴结果排版, 附上我的 Prompt

#### Claude提示词:
- 请调整上述文件的格式, 从而保证一行英文, 对应一行音标, 方便打印和在纸上记录笔记, 谢谢.
- 请把句子的文本设为 20 号字, 音标的文本设为 16 号字. 使用 html 输出.
然后把 html code 复制到 vscode, 保存为 abc.html, 使用 chrom 打开, 并打印即可.

#### 最后带音标的句子, 打印成品效果
![打印效果一行句子一行音标](https://github.com/ZuodaoTech/everyone-can-use-english/assets/105504077/e4c567e2-9550-4b99-82b0-992e47f09e80)

# 需求: 希望提供全文(含音标)下载功能. 
实现老师的训练方法-初期学习打印出全文含音标内容.

**Comment by an-lee** [comment]
原来这个需求是这么来的。

再等等，后续加一个。

**Comment by an-lee** [comment]
v0.3.1 版本已经实现。

![14cd508c-2723-49bc-bc40-4f39257647b0](https://github.com/user-attachments/assets/0e67dd03-b767-4c01-a2ce-9006278bb0f7)

**Comment by jemerci** [comment]
Wow, that's so cooool ~
