### ISSUE TITLE
单句循环时间间隔问题

### ISSUE THREAD

**Issue by SkyPan19** [ZuodaoTech/everyone-can-use-english#792]
跟读时，设置了单句循环模式，选中跟读一句话中的后半段时，每次系统播放循环的间隔时间有点长。等不及它播放时，当我再次按空格播放时又会和系统的自动播放冲突；所以单句循环模式的间隔时间能缩短吗？

**Comment by SkyPan19** [comment]
意思是，你们已经知道这是bug了吗？ps：我看没人回复我，多了红色字体的两个字“错误”。

**Comment by an-lee** [comment]
> 意思是，你们已经知道这是bug了吗？ps：我看没人回复我，多了红色字体的两个字“错误”。

是的。后面会修复。

**Comment by an-lee** [comment]
下载最新版 [v0.3.4](https://1000h.org/enjoy-app/install.html) 试试吧，应该已经修复了。
