### ISSUE TITLE
近两个版本常常出现的播放错误

### ISSUE THREAD

**Issue by JIM4ME** [ZuodaoTech/everyone-can-use-english#816]
设备：M2 macbook air 丐版
系统：最新
enjoy版本：0.2.15-0.3
问题：常常在进行数次语音评分后出现无法播出音频的故障，需要退出之gpt对话页面重新进入才可以再次播放。但并不能排除再次出现该故障现场的可能。数次故障后，在退出到gpt页面后也不能修复该问题，只能直接重启enjoy才能解决。
<img width="1470" alt="截屏2024-07-13 20 53 11" src="https://github.com/user-attachments/assets/24219018-6f49-4829-b1ea-bf6371fd14a7">

另外，有时后进行评分还会出现如下问题，但这个问题不严重，只需要退出评分再重进即可。
<img width="1470" alt="截屏2024-07-13 21 26 11" src="https://github.com/user-attachments/assets/13f4d664-5789-41ab-8896-46091cd1df97">

最后一个小优化，录音快捷键可修改，不一定为R
<img width="1470" alt="截屏2024-07-13 22 45 36" src="https://github.com/user-attachments/assets/58d9c111-05bc-4e99-8f36-77312fe6bb7e">

**Comment by an-lee** [comment]
> 最后一个小优化，录音快捷键可修改，不一定为R

快捷键都是可以修改的，在 `软件设置` / `快捷键` 里可以改。点击快捷键就可以修改了。

> 问题：常常在进行数次语音评分后出现无法播出音频的故障，需要退出之gpt对话页面重新进入才可以再次播放。但并不能排除再次出现该故障现场的可能。数次故障后，在退出到gpt页面后也不能修复该问题，只能直接重启enjoy才能解决。

这个问题我一直在努力复现。如果有更多线索，可以随时再补充。

**Comment by JIM4ME** [comment]
就我使用而言，大概率出现在录音及发音评分来回切的时候就会出现。例如，录一遍，然后评分，然后再录一遍，这就很容易触发这个bug。多次触发这个bug后，就得退出软件才能修复。

**Comment by JIM4ME** [comment]
>快捷键都是可以修改的，在 软件设置 / 快捷键 里可以改。点击快捷键就可以修改了。

这个我没表达清楚。我的意思是，修改快捷键后，文字提示不会跟着改变。

**Comment by an-lee** [comment]
> > 快捷键都是可以修改的，在 软件设置 / 快捷键 里可以改。点击快捷键就可以修改了。
> 
> 这个我没表达清楚。我的意思是，修改快捷键后，文字提示不会跟着改变。

哦哦，改好了： https://github.com/ZuodaoTech/everyone-can-use-english/commit/e2ad240023ac08de83375722cd78750f144fe629

**Comment by an-lee** [comment]
下载最新版 [v0.3.4](https://1000h.org/enjoy-app/install.html) 试试吧，应该已经修复了。

**Comment by JIM4ME** [comment]
已测试，今晚测试中没有出现该错误。但是好像还是需要科学上网的样子
