### ISSUE TITLE
升级到最新版（0.3.1）后，每句首单词会默认高亮并闪烁，空格键或播放按钮需要点两到三次才能播放整句

### ISSUE THREAD

**Issue by imxw** [ZuodaoTech/everyone-can-use-english#838]
![image](https://github.com/user-attachments/assets/62182ec9-35a9-4415-bb73-917238d4a05c)

**Comment by imxw** [comment]
降级后恢复正常
![image](https://github.com/user-attachments/assets/f33fbbdf-5e1f-43c9-a053-02b9e141e974)

**Comment by JIM4ME** [comment]
升级后我也遇到这个情况，特别在录音时会一致闪烁。

https://github.com/user-attachments/assets/e46b5280-3700-450e-b062-427091f127c6
