### ISSUE TITLE
需要点击两次才能播放的bug依旧纯在

### ISSUE THREAD

**Issue by JIM4ME** [ZuodaoTech/everyone-can-use-english#861]
环境：m2 macbookair 丐版
os：最新
enjoy版本：0.3.2
问题如题

https://github.com/user-attachments/assets/b30251db-81b5-47ae-964d-852ad80a65ab

**Comment by SkyPan19** [comment]
我也是

**Comment by an-lee** [comment]
不是需要点击两次，是需要等一会。应该是页面还没加载好，你就点了第一次

**Comment by an-lee** [comment]
到这里下载一个安装包试试看，https://github.com/ZuodaoTech/everyone-can-use-english/actions/runs/10153599567

**Comment by an-lee** [comment]
直接下载最新版 [v0.3.4](https://1000h.org/enjoy-app/install.html) 试试吧，应该已经修复了。

**Comment by JIM4ME** [comment]
已测试，确实已经修复
