### ISSUE TITLE
enjoy0.2.0之后的版本whisper不可用

### ISSUE THREAD

**Issue by shimeiyou** [ZuodaoTech/everyone-can-use-english#892]
ubuntu24.04

**Comment by an-lee** [comment]
可能是编译的 whisper 跟你的机器有不兼容，你可以这样

1. 自行将 [whisper.cpp](https://github.com/ggerganov/whisper.cpp) 编译一下；
2. 将编译得到 `main` 文件复制至 `/EnjoyLibrary/whisper/` 文件夹下

这样 Enjoy 会优先使用你的 `main` 文件执行。

**Comment by shimeiyou** [comment]
> 可能是编译的 whisper 跟你的机器有不兼容，你可以这样
> 
> 
> 
> 1. 自行将 [whisper.cpp](https://github.com/ggerganov/whisper.cpp) 编译一下；
> 
> 2. 将编译得到 `main` 文件复制至 `/EnjoyLibrary/whisper/` 文件夹下
> 
> 
> 
> 这样 Enjoy 会优先使用你的 `main` 文件执行。

**按照方法解决**
