### ISSUE TITLE
3.3智能翻译分析句子不可用

### ISSUE THREAD

**Issue by YJL626** [ZuodaoTech/everyone-can-use-english#893]
![image](https://github.com/user-attachments/assets/578016c6-a83c-4442-822c-afa8571ee20a)
![image](https://github.com/user-attachments/assets/fdddc74d-70b0-4b01-8512-4e49decefbd7)

**Comment by an-lee** [comment]
#894 修复了，不过要等下一次发版。

暂时有两个解决办法：

1. 在 软件设置 / AI 默认引擎 修改为 EnjoyAI；
2. 回退到 v0.3.2 版本先用着

**Comment by an-lee** [comment]
下载最新版 [v0.3.4](https://1000h.org/enjoy-app/install.html) 试试吧，应该已经修复了。
