### ISSUE TITLE
Windows 11 点击shadowing exercise 进入的界面播放按钮异常

### ISSUE THREAD

**Issue by treeliu** [ZuodaoTech/everyone-can-use-english#895]
录了个屏
https://www.awesomescreenshot.com/video/29905843?key=45a75f84367f372808b56798e34b5470

**Comment by an-lee** [comment]
Enjoy 版本是多少？

**Comment by treeliu** [comment]
> Enjoy 版本是多少？

v0.3.3

**Comment by treeliu** [comment]
补充了个录屏，发现这个问题好像和播放源有关。
https://www.awesomescreenshot.com/video/29957680?key=2529f7bd78f7ecc6ba85d0255b3f3eba

**Comment by an-lee** [comment]
到这里下载安装包，再试试看这个 bug 修好了没： https://github.com/ZuodaoTech/everyone-can-use-english/actions/runs/10153590446

**Comment by treeliu** [comment]
> 到这里下载安装包，再试试看这个 bug 修好了没： https://github.com/ZuodaoTech/everyone-can-use-english/actions/runs/10153590446
Fixed~ Good job!
