### ISSUE TITLE
创建ai角色一直加载

### ISSUE THREAD

**Issue by JIM4ME** [ZuodaoTech/everyone-can-use-english#905]
<img width="1470" alt="截屏2024-07-25 22 54 01" src="https://github.com/user-attachments/assets/1143e057-3959-4c7d-b9f9-fe1d396fd747">

在科学上网的前提下依然出现该问题

**Comment by JIM4ME** [comment]
版本：v.0.3.3

**Comment by Zhangjuanlli** [comment]
遇到同样的问题，期待解决  @lyricat

**Comment by lyricat** [comment]
看上去需要科学上网

> 遇到同样的问题，期待解决 @lyricat

**Comment by Zhangjuanlli** [comment]
> 看上去需要科学上网
> 
> > 遇到同样的问题，期待解决 @lyricat

科学上网状态了
