### ISSUE TITLE
翻译bug

### ISSUE THREAD

**Issue by JIM4ME** [ZuodaoTech/everyone-can-use-english#906]
<img width="1470" alt="截屏2024-07-28 20 21 23" src="https://github.com/user-attachments/assets/812df2bb-16c7-4196-9bc5-8a357d6e8fe8">

**Comment by an-lee** [comment]
参考这里： https://github.com/ZuodaoTech/everyone-can-use-english/issues/893#issuecomment-2251795219

**Comment by JIM4ME** [comment]
我遇到这个bug是时好时坏
