### ISSUE TITLE
播放按键失灵问题

### ISSUE THREAD

**Issue by Maoxin1** [ZuodaoTech/everyone-can-use-english#923]
播放键（无论是直接点空格键还是直接鼠标点击）经常会出现按很多次都不播放的情况，同时也会在某个时刻突然又可以播放的情况，这个情况很影响我的拉练效率，请问我应该怎么解决呀？

**Comment by an-lee** [comment]
到这里下载这个安装包试试看，https://github.com/ZuodaoTech/everyone-can-use-english/actions/runs/10153599567

**Comment by SkyPan19** [comment]
> 到这里下载这个安装包试试看，https://github.com/ZuodaoTech/everyone-can-use-english/actions/runs/10153599567

你好，请教下载后咋用呢？不懂怎么操作。
![屏幕截图 2024-08-03 202517](https://github.com/user-attachments/assets/b06e406b-ead3-444f-9931-937d0c6e5310)

**Comment by an-lee** [comment]
哦，那个是苹果电脑的，你的是 windows，那应该下这个 https://github.com/ZuodaoTech/everyone-can-use-english/actions/runs/10153590446

**Comment by an-lee** [comment]
直接下载最新版 [v0.3.4](https://1000h.org/enjoy-app/install.html) 试试吧，应该已经修复了。
