### ISSUE TITLE
youtube clash后 timeout

### ISSUE THREAD

**Issue by AIMWLI** [ZuodaoTech/everyone-can-use-english#941]
![image](https://github.com/user-attachments/assets/7f73df5c-cc80-4cab-80ef-a1517ea7269f)
浏览器正常能打开观看
设置里设置代理后也无法添加视频

**Comment by m1n99** [comment]
它使用的是youtubedr这个程序去下载油管视频，你需要手动设置一下两个环境变量：

HTTP_PROXY=http://127.0.0.1:7890
HTTPS_PROXY=http://127.0.0.1:7890

[youtubedr github](https://github.com/kkdai/youtube)

在[downloader.go](https://github.com/kkdai/youtube/blob/master/cmd/youtubedr/downloader.go)中有如下代码：
```go
func getDownloader() *ytdl.Downloader {
	if downloader != nil {
		return downloader
	}

	proxyFunc := httpproxy.FromEnvironment().ProxyFunc()
	httpTransport := &http.Transport{
		// Proxy: http.ProxyFromEnvironment() does not work. Why?
		Proxy: func(r *http.Request) (uri *url.URL, err error) {
			return proxyFunc(r.URL)
		},
		IdleConnTimeout:       60 * time.Second,
		TLSHandshakeTimeout:   10 * time.Second,
		ExpectContinueTimeout: 1 * time.Second,
		ForceAttemptHTTP2:     true,
		DialContext: (&net.Dialer{
			Timeout:   30 * time.Second,
			KeepAlive: 30 * time.Second,
		}).DialContext,
	}

	youtube.SetLogLevel(logLevel)

	if insecureSkipVerify {
		youtube.Logger.Info("Skip server certificate verification")
		httpTransport.TLSClientConfig = &tls.Config{
			InsecureSkipVerify: true,
		}
	}

	downloader = &ytdl.Downloader{
		OutputDir: outputDir,
	}
	downloader.HTTPClient = &http.Client{Transport: httpTransport}

	return downloader
}
```

代码中`proxyFunc := httpproxy.FromEnvironment().ProxyFunc()`使用的是go的http库，其中[proxy.go](https://github.com/golang/net/blob/master/http/httpproxy/proxy.go)中存在如下代码：
```go
func FromEnvironment() *Config {
	return &Config{
		HTTPProxy:  getEnvAny("HTTP_PROXY", "http_proxy"),
		HTTPSProxy: getEnvAny("HTTPS_PROXY", "https_proxy"),
		NoProxy:    getEnvAny("NO_PROXY", "no_proxy"),
		CGI:        os.Getenv("REQUEST_METHOD") != "",
	}
}
```
可以看出youtubedr这个下载器程序是从系统环境变量中取读取代理配置的。

希望对你有帮助！

**Comment by bluechallenge** [comment]
> 它使用的是youtubedr这个程序去下载油管视频，你需要手动设置一下两个环境变量：
> 
> HTTP_PROXY=http://127.0.0.1:7890 HTTPS_PROXY=http://127.0.0.1:7890
> 
> [youtubedr github](https://github.com/kkdai/youtube)
> 
> 在[downloader.go](https://github.com/kkdai/youtube/blob/master/cmd/youtubedr/downloader.go)中有如下代码：
> 
> ```go
> func getDownloader() *ytdl.Downloader {
> 	if downloader != nil {
> 		return downloader
> 	}
> 
> 	proxyFunc := httpproxy.FromEnvironment().ProxyFunc()
> 	httpTransport := &http.Transport{
> 		// Proxy: http.ProxyFromEnvironment() does not work. Why?
> 		Proxy: func(r *http.Request) (uri *url.URL, err error) {
> 			return proxyFunc(r.URL)
> 		},
> 		IdleConnTimeout:       60 * time.Second,
> 		TLSHandshakeTimeout:   10 * time.Second,
> 		ExpectContinueTimeout: 1 * time.Second,
> 		ForceAttemptHTTP2:     true,
> 		DialContext: (&net.Dialer{
> 			Timeout:   30 * time.Second,
> 			KeepAlive: 30 * time.Second,
> 		}).DialContext,
> 	}
> 
> 	youtube.SetLogLevel(logLevel)
> 
> 	if insecureSkipVerify {
> 		youtube.Logger.Info("Skip server certificate verification")
> 		httpTransport.TLSClientConfig = &tls.Config{
> 			InsecureSkipVerify: true,
> 		}
> 	}
> 
> 	downloader = &ytdl.Downloader{
> 		OutputDir: outputDir,
> 	}
> 	downloader.HTTPClient = &http.Client{Transport: httpTransport}
> 
> 	return downloader
> }
> ```
> 
> 代码中`proxyFunc := httpproxy.FromEnvironment().ProxyFunc()`使用的是go的http库，其中[proxy.go](https://github.com/golang/net/blob/master/http/httpproxy/proxy.go)中存在如下代码：
> 
> ```go
> func FromEnvironment() *Config {
> 	return &Config{
> 		HTTPProxy:  getEnvAny("HTTP_PROXY", "http_proxy"),
> 		HTTPSProxy: getEnvAny("HTTPS_PROXY", "https_proxy"),
> 		NoProxy:    getEnvAny("NO_PROXY", "no_proxy"),
> 		CGI:        os.Getenv("REQUEST_METHOD") != "",
> 	}
> }
> ```
> 
> 可以看出youtubedr这个下载器程序是从系统环境变量中取读取代理配置的。
> 
> 希望对你有帮助！

感谢分享，说说我这里的情况。

**版本信息**
macOS Ventura 13.6.8
ClashX v1.96.2
x86 Enjoy v0.3.4

**步骤**
1. 打开 Terminal，编辑配置文件：nano ~/.zshrc
2. 添加两个全局变量：

export HTTP_PROXY="http://127.0.0.1:7890/"
export HTTPS_PROXY="http://127.0.0.1:7890/"

3. 保存并重新加载配置文件：source ~/.zshrc
4. 通过 Terminal 打开 Enjoy：open -a /Applications/Enjoy.app
5. 无论ClashX的配置是 "Global" 还是 "Rule" 以及是否 Enjoy Proxy Setting，都可以正常下载 YouTube 视频
6. 有尝试过只配置 ClashX Global模式以及打开 Enjoy Proxy Settings，但都无法下载 YouTube 视频

**问题**

虽然通过上述方法可以正常下载 YouTube视频，但每次都得通过 Terminal 打开 Enjoy，稍微有点麻烦。想请教 @m1n99 @an-lee :
_Enjoy Proxy Settings 配置是否有可能直接给 youtubedr 用，从而更新 HTTP_PROXY 和 HTTPS_PROXY，以实现正常下载？_

**Comment by m1n99** [comment]
@bluechallenge 可以的，我已经拉取代码建立新的分支在我本地运行调试过了。

实现思路就是子程序调用youtubedr程序去下载油管视频时，为其设置HTTP_PROXY和HTTPS_PROXY这两个环境变量的值为 enjoy 的代理 url。

## node.js child_process模块关键的两个函数
[child_process.exec(command[, options][, callback])](https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback)
[child_process.spawn(command[, args][, options])](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options)

其中options参数中都有一个env参数，该参数就是为子程序设置环境变量。

## enjoy 关键代码
enjoy/src/main/youtubedr.ts
```typescript
......

return new Promise((resolve, reject) => {
      const proc = spawn(
        this.binFile,
        [
          "download",
          url,
          `--quality=${quality || "medium"}`,
          `--filename=${filename}`,
          `--directory=${directory}`,
        ],
        {
          timeout: TEN_MINUTES,
          signal: this.abortController.signal,
          env: this.proxyEnv()
        }
      );

......

async info(url: string): Promise<YoutubeInfoType> {
    const command = [this.binFile, "info", `"${url}"`, "--format json"].join(
      " "
    );
    return new Promise((resolve, reject) => {
      exec(
        command,
        {
          timeout: ONE_MINUTE,
          env: this.proxyEnv()
        },
        (error, stdout, stderr) => {
          if (error) {
            logger.error(error);
            reject(error);
          }

          if (stderr) {
            logger.error(stderr);
            reject(new Error(stderr));
          }

          if (stdout) {
            logger.debug(stdout);
            try {
              const info = JSON.parse(stdout);
              resolve(info);
            } catch (err) {
              logger.error("json result failed to parse", err);
              reject(stdout);
            }
          }

          reject(new Error("Youtubedr info failed: unknown error"));
        }
      );
    });
  }

......

/**
   * 代理环境变量配置
   * @returns env object
   */
  proxyEnv = () => {
    // 保留当前环境变量
    let env = {...process.env}
    const proxyConfig = settings.getSync("proxy") as ProxyConfigType;
    if (proxyConfig.enabled && proxyConfig.url) {
      // 设置 enjoy 的代理 url
      env["HTTP_PROXY"] = proxyConfig.url;
      env["HTTPS_PROXY"] = proxyConfig.url;
    }
    return env
  }
```

@an-lee 我已提交一个pr，不过目前我并没有mac系统来进行测试，理论上应该是和操作系统无关的^_^

**Comment by an-lee** [comment]
v0.4.0 已经上线改功能。
