### ISSUE TITLE
无法使用github账号完成登录

### ISSUE THREAD

**Issue by 2AndreyZ** [ZuodaoTech/everyone-can-use-english#948]
![Snipaste_2024-08-08_20-43-46](https://github.com/user-attachments/assets/0e46ba52-e0fa-4f56-be51-b48e660e1cba)
最新版本，用Github账号无法完成登录，这是我网络问题吗？我访问其他的都正常。
点击重新登录，一直在以下这个页面，并提示“nerwork  error”
![image](https://github.com/user-attachments/assets/ee3ebec2-1e3c-4013-9721-427d6ee4d707)

**Comment by an-lee** [comment]
参考这里说明：[常见问题](https://1000h.org/enjoy-app/faq.html#%E6%80%BB%E6%98%AF%E6%8A%A5%E7%BD%91%E7%BB%9C%E9%94%99%E8%AF%AF%E6%80%8E%E4%B9%88%E5%8A%9E)

**Comment by an-lee** [comment]
简单来说，需要全局科学上网，或者在“高级设置”里配置一下代理。

**Comment by 2AndreyZ** [comment]
非常感谢！我配置了后解决了！
