### ISSUE TITLE
0.3.4版一按设置就出错

### ISSUE THREAD

**Issue by BoosterCore** [ZuodaoTech/everyone-can-use-english#951]
![image](https://github.com/user-attachments/assets/64512fd6-7517-43b5-8cfa-ad2abf0cd7a7)

**Comment by an-lee** [comment]
是有个bug，如果之前编辑过 OpenAI 的自定义模型的话，会触发。下个版本会修复的。
临时解决办法，可以下载这个[临时打包的版本](https://github.com/ZuodaoTech/everyone-can-use-english/actions/runs/10329343647)先用着。

**Comment by an-lee** [comment]
Fixed in #945

**Comment by BoosterCore** [comment]
非常感谢

**Comment by an-lee** [comment]
v.0.4.0 已经发布了。
