### ISSUE TITLE
对比快捷键不生效

### ISSUE THREAD

**Issue by KayWu** [ZuodaoTech/everyone-can-use-english#987]
版本：mac 0.4.0

可以点击界面上的对比按钮进行录音的对比，但是按快捷键 c 没有效果。即使换一个快捷键，同样没有效果。
<img width="271" alt="image" src="https://github.com/user-attachments/assets/c30f6e52-52cc-4293-9b82-ade67ca5b986">

**Comment by an-lee** [comment]
Fixed in https://github.com/ZuodaoTech/everyone-can-use-english/pull/981/commits/0e43e2a37d89f3ec4ef067782b3dd207662588df

**Comment by an-lee** [comment]
v0.4.1 已经修复。
