### ISSUE TITLE
句子文本转语音后，”history“等单词的音标问题

### ISSUE THREAD

**Issue by SkyPan19** [ZuodaoTech/everyone-can-use-english#991]
文本转语音后的音标显示为/ˈhɪstɚri/，但是与实际系统读音没对上；我去查了其它AI的美式英语发音显示为/ˈhɪstri/，这个音标与系统声音是对上的。

以及之前也发现一些系统朗读声音和音标没有对上的，然后又得去另外找AI确认正确的美式音标和发音，有些费时间，影响朗读。

**Comment by SkyPan19** [comment]
![屏幕截图 2024-08-18 193957](https://github.com/user-attachments/assets/e29ea96e-3dab-4f36-9606-98dc13a795bb)
![屏幕截图 2024-08-18 194031](https://github.com/user-attachments/assets/39e51a98-d28e-43b0-8e93-9e7c227ea8f9)

**Comment by an-lee** [comment]
自动生成的音标确实不一定唯一准确
